name: csl-app
region: nyc

# Backend Service
services:
  - name: backend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /backend
    build_command: npm install && npx prisma generate && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /api
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: JWT_SECRET
        value: YOUR_JWT_SECRET
        type: SECRET
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: STRIPE_SECRET_KEY
        value: YOUR_STRIPE_SECRET_KEY
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        value: YOUR_STRIPE_WEBHOOK_SECRET
        type: SECRET
      - key: FRONTEND_URL
        value: ${apps.csl-frontend.PUBLIC_URL}
      - key: STRIPE_PRICE_ID_MONTHLY
        value: YOUR_MONTHLY_PRICE_ID
      - key: STRIPE_PRICE_ID_ANNUAL
        value: YOUR_ANNUAL_PRICE_ID

  # Frontend Static Site with SPA routing
  - name: csl-frontend
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm install && npm run build
    output_dir: dist
    environment_slug: static-site
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${apps.backend.PUBLIC_URL}/api

# Database
databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    cluster_name: csl-db
    db_name: csl
    db_user: csl_user
